"""create_news_data_table

Revision ID: bbd2359d1afe
Revises: 905fcd26e525
Create Date: 2025-06-01 18:44:20.068099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbd2359d1afe'
down_revision: Union[str, None] = '905fcd26e525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('source_title', sa.String(), nullable=False),
    sa.Column('news_title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('currencies', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('votes_positive', sa.Integer(), nullable=True),
    sa.Column('votes_negative', sa.Integer(), nullable=True),
    sa.Column('votes_important', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_news_data_content_hash'), 'news_data', ['content_hash'], unique=True)
    op.create_index(op.f('ix_news_data_id'), 'news_data', ['id'], unique=False)
    op.create_index(op.f('ix_news_data_published_at'), 'news_data', ['published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_data_published_at'), table_name='news_data')
    op.drop_index(op.f('ix_news_data_id'), table_name='news_data')
    op.drop_index(op.f('ix_news_data_content_hash'), table_name='news_data')
    op.drop_table('news_data')
    # ### end Alembic commands ###
